fekade = User.create(name: "Fekade", description: "Originally from Ethiopia, i moved the states when i was a young boy at just six years old. I love the Ethiopian community and would love to attend events in the area!")



ethiopianDayFestival = Event.create(user: fekade, title: "Ethiopian Day Festival, of Colorado", date: "September 14, 2018", time: "10", description: "The Annual Ethiopian Day Festival, Presented by Colorado Ethiopian Community, is an annual event held for the purpose of bringing the community together and to help support the young Ethiopian to excel in every of their field. Ethiopian Day will draws a large family audience of over 3,500 festival-goers this year. This two-day event features arts and crafts, business and non-profit exhibitors, music, fashion show, cultural food, Cultural events, and a great selection of food and entertainment. Ethiopian Day Festival is promoted throughout the Denver metro area and Aurora through local newspapers, small businesses, and homeowners associations, civic and church groups. Sponsors use the event as an opportunity for recognition and marketing, to entertain clients and guests and to support the community!", location: "Bicentennial Park 13655 East Alameda Avenue, Aurora, CO 80012")
ethiopianNewYear = Event.create(user: fekade, title: "New Years Celebration", date: "September 16, 2018", time: "3:00 - 6:00 PM", description: "The Executive Committee of the Colorado Ethiopian Community (CEC) is pleased to invite you to take part in the 2011 Ethiopian New Year. This is an important celebration for the community so join the CEC for an Ethiopian New Year filled with the spirit of excitement and hope. The CEC will use this event to show support to the effort the new Prime Minister, Dr Abiy Ahmed is making to the people of Ethiopia in order to establish a democratic system in the country of Ethiopia. This event will feature traditional Ethiopian music, recreational programs, food and sports!", location: "William C. Hinkley High School 1250 Chambers Rd, Aurora, CO 80011")
difretMovieScreening = Event.create(user: fekade, title: "Difret Movie Screening", date: "October 25, 2019", time: "6:00 PM", description: "Based on the true story of a young Ethiopian girl kidnapped for marriage and put on trial for murder after killing her abductor. A female lawyer and women’s rights activist, Meaza Ashenafi (now newly-appointed first female President of Ethiopia’s Federal Supreme Court), takes on her defense!", location: "Village Exchange Center 1609 Havana Street Aurora, CO 80010")




